{
 "title": "Batangas-Upgrade_services",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "BATS0002CIBE001 | Bundle-Ether20000",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'BATS0002CIBE001' AND \"ifDescription\" = 'Bundle-Ether20000') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "BATS0002CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "BATS0002CIBE001 | TenGigE0/1/0/4",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'BATS0002CIBE001' AND \"ifDescription\" = 'TenGigE0/1/0/4') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "BATS0002CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "BATS0002CIBE001 | Bundle-Ether60002",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'BATS0002CIBE001' AND \"ifDescription\" = 'Bundle-Ether60002') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "BATS0002CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "BATS0002CIBE001 | TenGigE0/1/0/14",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'BATS0002CIBE001' AND \"ifDescription\" = 'TenGigE0/1/0/14') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "BATS0002CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "BATS0002CIBE001 | TenGigE0/1/0/18",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'BATS0002CIBE001' AND \"ifDescription\" = 'TenGigE0/1/0/18') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "BATS0002CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "BATS0002CIBE001 | Bundle-Ether1001",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'BATS0002CIBE001' AND \"ifDescription\" = 'Bundle-Ether1001') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "BATS0002CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "BATS0002CIBE001 | HundredGigE0/0/0/17",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'BATS0002CIBE001' AND \"ifDescription\" = 'HundredGigE0/0/0/17') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "BATS0002CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "BATS0002CIBE001 | HundredGigE0/7/0/17",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'BATS0002CIBE001' AND \"ifDescription\" = 'HundredGigE0/7/0/17') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "BATS0002CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "BATS0002CIBE002 | TenGigE0/1/0/13",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'BATS0002CIBE002' AND \"ifDescription\" = 'TenGigE0/1/0/13') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "BATS0002CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "BATS0002CIBE002 | Bundle-Ether20000",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'BATS0002CIBE002' AND \"ifDescription\" = 'Bundle-Ether20000') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "BATS0002CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "BATS0002CIBE002 | Bundle-Ether60002",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'BATS0002CIBE002' AND \"ifDescription\" = 'Bundle-Ether60002') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "BATS0002CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "BATS0002CIBE002 | Bundle-Ether1001",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'BATS0002CIBE002' AND \"ifDescription\" = 'Bundle-Ether1001') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "BATS0002CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "BATS0002CIBE002 | HundredGigE0/0/0/17",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'BATS0002CIBE002' AND \"ifDescription\" = 'HundredGigE0/0/0/17') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "BATS0002CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "BATS0002CIBE002 | HundredGigE0/7/0/17",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'BATS0002CIBE002' AND \"ifDescription\" = 'HundredGigE0/7/0/17') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "BATS0002CIBE002" }
     ]
    }
   ]
  }
 ]
}