{
 "title": "SXLPXSXLCIBE001_SXLPXSXLCIBE002_infra",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "SXLPXSXLCIBE001 | HundredGigE0/0/0/0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SXLPXSXLCIBE001' AND \"ifDescription\" = 'HundredGigE0/0/0/0') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SXLPXSXLCIBE001" }
     ]
    }
   ]
  },
  {
   "title": "SXLPXSXLCIBE001 | Bundle-Ether31",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SXLPXSXLCIBE001' AND \"ifDescription\" = 'Bundle-Ether31') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SXLPXSXLCIBE001" }
     ]
    }
   ]
  },
  {
   "title": "SXLPXSXLCIBE001 | HundredGigE0/7/0/5",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SXLPXSXLCIBE001' AND \"ifDescription\" = 'HundredGigE0/7/0/5') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SXLPXSXLCIBE001" }
     ]
    }
   ]
  },
  {
   "title": "SXLPXSXLCIBE001 | Bundle-Ether252",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SXLPXSXLCIBE001' AND \"ifDescription\" = 'Bundle-Ether252') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SXLPXSXLCIBE001" }
     ]
    }
   ]
  },
  {
   "title": "SXLPXSXLCIBE001 | HundredGigE0/0/0/1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SXLPXSXLCIBE001' AND \"ifDescription\" = 'HundredGigE0/0/0/1') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SXLPXSXLCIBE001" }
     ]
    }
   ]
  },
  {
   "title": "SXLPXSXLCIBE001 | Bundle-Ether10",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SXLPXSXLCIBE001' AND \"ifDescription\" = 'Bundle-Ether10') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SXLPXSXLCIBE001" }
     ]
    }
   ]
  },
  {
   "title": "SXLPXSXLCIBE002 | HundredGigE0/7/0/0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SXLPXSXLCIBE002' AND \"ifDescription\" = 'HundredGigE0/7/0/0') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SXLPXSXLCIBE002" }
     ]
    }
   ]
  },
  {
   "title": "SXLPXSXLCIBE002 | Bundle-Ether32",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SXLPXSXLCIBE002' AND \"ifDescription\" = 'Bundle-Ether32') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SXLPXSXLCIBE002" }
     ]
    }
   ]
  },
  {
   "title": "SXLPXSXLCIBE002 | HundredGigE0/7/0/5",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SXLPXSXLCIBE002' AND \"ifDescription\" = 'HundredGigE0/7/0/5') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SXLPXSXLCIBE002" }
     ]
    }
   ]
  },
  {
   "title": "SXLPXSXLCIBE002 | Bundle-Ether252",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SXLPXSXLCIBE002' AND \"ifDescription\" = 'Bundle-Ether252') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SXLPXSXLCIBE002" }
     ]
    }
   ]
  },
  {
   "title": "SXLPXSXLCIBE002 | HundredGigE0/0/0/1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SXLPXSXLCIBE002' AND \"ifDescription\" = 'HundredGigE0/0/0/1') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SXLPXSXLCIBE002" }
     ]
    }
   ]
  },
  {
   "title": "SXLPXSXLCIBE002 | Bundle-Ether10",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SXLPXSXLCIBE002' AND \"ifDescription\" = 'Bundle-Ether10') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SXLPXSXLCIBE002" }
     ]
    }
   ]
  },
  {
   "title": "LCN04117CIBP001 | HundredGigE0/0/0/2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'LCN04117CIBP001' AND \"ifDescription\" = 'HundredGigE0/0/0/2') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "LCN04117CIBP001" }
     ]
    }
   ]
  },
  {
   "title": "LCN04117CIBP001 | Bundle-Ether39",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'LCN04117CIBP001' AND \"ifDescription\" = 'Bundle-Ether39') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "LCN04117CIBP001" }
     ]
    }
   ]
  },
  {
   "title": "SXL04178CICU001 | HundredGigE0/0/2/0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SXL04178CICU001' AND \"ifDescription\" = 'HundredGigE0/0/2/0') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SXL04178CICU001" }
     ]
    }
   ]
  },
  {
   "title": "SXL04178CICU001 | Bundle-Ether201",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SXL04178CICU001' AND \"ifDescription\" = 'Bundle-Ether201') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SXL04178CICU001" }
     ]
    }
   ]
  },
  {
   "title": "SXLPXSXLCIBE002 | HundredGigE0/0/0/1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SXLPXSXLCIBE002' AND \"ifDescription\" = 'HundredGigE0/0/0/1') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SXLPXSXLCIBE002" }
     ]
    }
   ]
  },
  {
   "title": "SXLPXSXLCIBE002 | Bundle-Ether10",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SXLPXSXLCIBE002' AND \"ifDescription\" = 'Bundle-Ether10') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SXLPXSXLCIBE002" }
     ]
    }
   ]
  },
  {
   "title": "LCN04117CIBP002 | HundredGigE0/1/0/2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'LCN04117CIBP002' AND \"ifDescription\" = 'HundredGigE0/1/0/2') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "LCN04117CIBP002" }
     ]
    }
   ]
  },
  {
   "title": "LCN04117CIBP002 | Bundle-Ether40",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'LCN04117CIBP002' AND \"ifDescription\" = 'Bundle-Ether40') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "LCN04117CIBP002" }
     ]
    }
   ]
  },
  {
   "title": "SXL04178CICU001 | HundredGigE0/1/2/0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SXL04178CICU001' AND \"ifDescription\" = 'HundredGigE0/1/2/0') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SXL04178CICU001" }
     ]
    }
   ]
  },
  {
   "title": "SXL04178CICU001 | Bundle-Ether202",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SXL04178CICU001' AND \"ifDescription\" = 'Bundle-Ether202') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SXL04178CICU001" }
     ]
    }
   ]
  },
  {
   "title": "SXLPXSXLCIBE001 | HundredGigE0/0/0/1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SXLPXSXLCIBE001' AND \"ifDescription\" = 'HundredGigE0/0/0/1') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SXLPXSXLCIBE001" }
     ]
    }
   ]
  },
  {
   "title": "SXLPXSXLCIBE001 | Bundle-Ether1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SXLPXSXLCIBE001' AND \"ifDescription\" = 'Bundle-Ether1') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SXLPXSXLCIBE001" }
     ]
    }
   ]
  }
 ]
}