{
 "title": "SUB00527CIBE001_SUB00527CIBE002_upgrade_infra",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "SUB00527CIBE001 | HundredGigE0/0/0/0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE001' AND \"ifDescription\" = 'HundredGigE0/0/0/0') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE001 | Bundle-Ether31",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE001' AND \"ifDescription\" = 'Bundle-Ether31') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE001 | HundredGigE0/7/0/0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE001' AND \"ifDescription\" = 'HundredGigE0/7/0/0') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE001 | Bundle-Ether32",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE001' AND \"ifDescription\" = 'Bundle-Ether32') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE001 | HundredGigE0/0/0/1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE001' AND \"ifDescription\" = 'HundredGigE0/0/0/1') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE001 | Bundle-Ether10",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE001' AND \"ifDescription\" = 'Bundle-Ether10') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE001 | HundredGigE0/0/0/3",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE001' AND \"ifDescription\" = 'HundredGigE0/0/0/3') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE001 | Bundle-Ether255",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE001' AND \"ifDescription\" = 'Bundle-Ether255') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE001 | HundredGigE0/0/0/12",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE001' AND \"ifDescription\" = 'HundredGigE0/0/0/12') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE001 | Bundle-Ether700",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE001' AND \"ifDescription\" = 'Bundle-Ether700') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE001 | HundredGigE0/7/0/3",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE001' AND \"ifDescription\" = 'HundredGigE0/7/0/3') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE001 | Bundle-Ether252",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE001' AND \"ifDescription\" = 'Bundle-Ether252') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE001 | HundredGigE0/7/0/4",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE001' AND \"ifDescription\" = 'HundredGigE0/7/0/4') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE001 | Bundle-Ether254",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE001' AND \"ifDescription\" = 'Bundle-Ether254') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE002 | HundredGigE0/0/0/0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE002' AND \"ifDescription\" = 'HundredGigE0/0/0/0') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE002 | Bundle-Ether31",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE002' AND \"ifDescription\" = 'Bundle-Ether31') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE002 | HundredGigE0/7/0/0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE002' AND \"ifDescription\" = 'HundredGigE0/7/0/0') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE002 | Bundle-Ether32",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE002' AND \"ifDescription\" = 'Bundle-Ether32') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE002 | HundredGigE0/0/0/1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE002' AND \"ifDescription\" = 'HundredGigE0/0/0/1') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE002 | Bundle-Ether10",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE002' AND \"ifDescription\" = 'Bundle-Ether10') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE002 | HundredGigE0/0/0/3",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE002' AND \"ifDescription\" = 'HundredGigE0/0/0/3') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE002 | Bundle-Ether255",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE002' AND \"ifDescription\" = 'Bundle-Ether255') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE002 | HundredGigE0/7/0/3",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE002' AND \"ifDescription\" = 'HundredGigE0/7/0/3') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE002 | Bundle-Ether252",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE002' AND \"ifDescription\" = 'Bundle-Ether252') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE002 | HundredGigE0/7/0/4",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE002' AND \"ifDescription\" = 'HundredGigE0/7/0/4') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE002 | Bundle-Ether252",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE002' AND \"ifDescription\" = 'Bundle-Ether252') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE002 | HundredGigE0/7/0/12",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE002' AND \"ifDescription\" = 'HundredGigE0/7/0/12') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE002 | Bundle-Ether701",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 118 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE002' AND \"ifDescription\" = 'Bundle-Ether701') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "MKTG3610CIBP001 | HundredGigE0/1/0/3",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'MKTG3610CIBP001' AND \"ifDescription\" = 'HundredGigE0/1/0/3') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "MKTG3610CIBP001" }
     ]
    }
   ]
  },
  {
   "title": "MKTG3610CIBP001 | Bundle-Ether46",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 127 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'MKTG3610CIBP001' AND \"ifDescription\" = 'Bundle-Ether46') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "MKTG3610CIBP001" }
     ]
    }
   ]
  },
  {
   "title": "SPC00E67CIBP002 | HundredGigE0/1/0/33",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SPC00E67CIBP002' AND \"ifDescription\" = 'HundredGigE0/1/0/33') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SPC00E67CIBP002" }
     ]
    }
   ]
  },
  {
   "title": "SPC00E67CIBP002 | Bundle-Ether42",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 136 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SPC00E67CIBP002' AND \"ifDescription\" = 'Bundle-Ether42') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SPC00E67CIBP002" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE002 | HundredGigE0/0/0/1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE002' AND \"ifDescription\" = 'HundredGigE0/0/0/1') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE002 | Bundle-Ether10",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 145 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE002' AND \"ifDescription\" = 'Bundle-Ether10') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "BLA00N55CICU001 | HundredGigE0/0/2/0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 154 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'BLA00N55CICU001' AND \"ifDescription\" = 'HundredGigE0/0/2/0') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "BLA00N55CICU001" }
     ]
    }
   ]
  },
  {
   "title": "BLA00N55CICU001 | Bundle-Ether255",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 154 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'BLA00N55CICU001' AND \"ifDescription\" = 'Bundle-Ether255') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "BLA00N55CICU001" }
     ]
    }
   ]
  },
  {
   "title": "OLGPXOLGCICU001 | HundredGigE0/0/2/0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 163 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'OLGPXOLGCICU001' AND \"ifDescription\" = 'HundredGigE0/0/2/0') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "OLGPXOLGCICU001" }
     ]
    }
   ]
  },
  {
   "title": "OLGPXOLGCICU001 | Bundle-Ether251",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 163 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'OLGPXOLGCICU001' AND \"ifDescription\" = 'Bundle-Ether251') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "OLGPXOLGCICU001" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CICU001 | HundredGigE0/7/0/4",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 172 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CICU001' AND \"ifDescription\" = 'HundredGigE0/7/0/4') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CICU001" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CICU001 | Bundle-Ether251",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 172 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CICU001' AND \"ifDescription\" = 'Bundle-Ether251') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CICU001" }
     ]
    }
   ]
  },
  {
   "title": "MKTG3610CIBP002 | HundredGigE0/1/0/3",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'MKTG3610CIBP002' AND \"ifDescription\" = 'HundredGigE0/1/0/3') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "MKTG3610CIBP002" }
     ]
    }
   ]
  },
  {
   "title": "MKTG3610CIBP002 | Bundle-Ether46",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 181 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'MKTG3610CIBP002' AND \"ifDescription\" = 'Bundle-Ether46') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "MKTG3610CIBP002" }
     ]
    }
   ]
  },
  {
   "title": "SPC00E67CIBP001 | HundredGigE0/7/0/0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 190 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SPC00E67CIBP001' AND \"ifDescription\" = 'HundredGigE0/7/0/0') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SPC00E67CIBP001" }
     ]
    }
   ]
  },
  {
   "title": "SPC00E67CIBP001 | Bundle-Ether42",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 190 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SPC00E67CIBP001' AND \"ifDescription\" = 'Bundle-Ether42') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SPC00E67CIBP001" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE001 | HundredGigE0/0/0/1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 199 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE001' AND \"ifDescription\" = 'HundredGigE0/0/0/1') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CIBE001 | Bundle-Ether10",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 199 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CIBE001' AND \"ifDescription\" = 'Bundle-Ether10') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "BLA00N55CICU001 | HundredGigE0/0/0/2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 208 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'BLA00N55CICU001' AND \"ifDescription\" = 'HundredGigE0/0/0/2') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "BLA00N55CICU001" }
     ]
    }
   ]
  },
  {
   "title": "BLA00N55CICU001 | Bundle-Ether256",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 208 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'BLA00N55CICU001' AND \"ifDescription\" = 'Bundle-Ether256') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "BLA00N55CICU001" }
     ]
    }
   ]
  },
  {
   "title": "OLGPXOLGCICU001 | HundredGigE0/1/2/0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 217 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'OLGPXOLGCICU001' AND \"ifDescription\" = 'HundredGigE0/1/2/0') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "OLGPXOLGCICU001" }
     ]
    }
   ]
  },
  {
   "title": "OLGPXOLGCICU001 | Bundle-Ether252",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 217 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'OLGPXOLGCICU001' AND \"ifDescription\" = 'Bundle-Ether252') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "OLGPXOLGCICU001" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CICU001 | HundredGigE0/1/2/0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 226 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CICU001' AND \"ifDescription\" = 'HundredGigE0/1/2/0') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CICU001" }
     ]
    }
   ]
  },
  {
   "title": "SUB00527CICU001 | Bundle-Ether252",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 226 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SUB00527CICU001' AND \"ifDescription\" = 'Bundle-Ether252') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SUB00527CICU001" }
     ]
    }
   ]
  }
 ]
}