{
 "title": "KAWS0016CIBE001_infra",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "KAWS0016CIBE001 | Bundle-Ether251",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CIBE001' AND \"ifDescription\" = 'Bundle-Ether251') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CIBE002 | Bundle-Ether251",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CIBE002' AND \"ifDescription\" = 'Bundle-Ether251') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CIBE001 | Bundle-Ether253",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CIBE001' AND \"ifDescription\" = 'Bundle-Ether253') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CIBE002 | Bundle-Ether253",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CIBE002' AND \"ifDescription\" = 'Bundle-Ether253') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CICU001 | Bundle-Ether251",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CICU001' AND \"ifDescription\" = 'Bundle-Ether251') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CICU001" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CICU001 | Bundle-Ether252",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CICU001' AND \"ifDescription\" = 'Bundle-Ether252') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CICU001" }
     ]
    }
   ]
  },
  {
   "title": "RSCS0075CICU001 | Bundle-Ether251",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'RSCS0075CICU001' AND \"ifDescription\" = 'Bundle-Ether251') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "RSCS0075CICU001" }
     ]
    }
   ]
  },
  {
   "title": "RSCS0075CICU001 | Bundle-Ether252",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'RSCS0075CICU001' AND \"ifDescription\" = 'Bundle-Ether252') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "RSCS0075CICU001" }
     ]
    }
   ]
  }
 ]
}