{
 "title": "KAWS0016CIBE002-Upgrade_infra",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "KAWS0016CIBE002 | Bundle-Ether10",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CIBE002' AND \"ifDescription\" = 'Bundle-Ether10') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CIBE002 | Bundle-Ether31",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CIBE002' AND \"ifDescription\" = 'Bundle-Ether31') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CIBE002 | Bundle-Ether32",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CIBE002' AND \"ifDescription\" = 'Bundle-Ether32') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CIBE002 | Bundle-Ether102",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CIBE002' AND \"ifDescription\" = 'Bundle-Ether102') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CIBE002 | Bundle-Ether105",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CIBE002' AND \"ifDescription\" = 'Bundle-Ether105') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CIBE002 | Bundle-Ether109",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CIBE002' AND \"ifDescription\" = 'Bundle-Ether109') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CIBE002 | Bundle-Ether110",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CIBE002' AND \"ifDescription\" = 'Bundle-Ether110') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CIBE002 | Bundle-Ether111",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CIBE002' AND \"ifDescription\" = 'Bundle-Ether111') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CIBE002 | Bundle-Ether116",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CIBE002' AND \"ifDescription\" = 'Bundle-Ether116') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CIBE002 | Bundle-Ether251",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CIBE002' AND \"ifDescription\" = 'Bundle-Ether251') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CIBE002 | Bundle-Ether253",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CIBE002' AND \"ifDescription\" = 'Bundle-Ether253') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CIBE002 | Bundle-Ether700",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CIBE002' AND \"ifDescription\" = 'Bundle-Ether700') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CIBE002 | Bundle-Ether701",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CIBE002' AND \"ifDescription\" = 'Bundle-Ether701') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CIBE002 | Bundle-Ether703",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CIBE002' AND \"ifDescription\" = 'Bundle-Ether703') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CIBE002 | Bundle-Ether704",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CIBE002' AND \"ifDescription\" = 'Bundle-Ether704') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CIBE002" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CIBE001 | Bundle-Ether10",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CIBE001' AND \"ifDescription\" = 'Bundle-Ether10') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CIBE001" }
     ]
    }
   ]
  },
  {
   "title": "MKTG3610CIBP002 | Bundle-Ether 51",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'MKTG3610CIBP002' AND \"ifDescription\" = 'Bundle-Ether 51') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "MKTG3610CIBP002" }
     ]
    }
   ]
  },
  {
   "title": "SPC00E67CIBP001 | Bundle-Ether47",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SPC00E67CIBP001' AND \"ifDescription\" = 'Bundle-Ether47') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SPC00E67CIBP001" }
     ]
    }
   ]
  },
  {
   "title": "SILS0012CICN001  | Bundle-Ether101",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'SILS0012CICN001 ' AND \"ifDescription\" = 'Bundle-Ether101') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SILS0012CICN001 " }
     ]
    }
   ]
  },
  {
   "title": "IMUS3559CICN001 | Bundle-Ether102",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'IMUS3559CICN001' AND \"ifDescription\" = 'Bundle-Ether102') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "IMUS3559CICN001" }
     ]
    }
   ]
  },
  {
   "title": "BCR00S33CICN001 | Bundle-Ether109",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'BCR00S33CICN001' AND \"ifDescription\" = 'Bundle-Ether109') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "BCR00S33CICN001" }
     ]
    }
   ]
  },
  {
   "title": "BCR00S33CICN002 | Bundle-Ether102",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'BCR00S33CICN002' AND \"ifDescription\" = 'Bundle-Ether102') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "BCR00S33CICN002" }
     ]
    }
   ]
  },
  {
   "title": "IDGS0097CICN001 | Bundle-Ether101",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'IDGS0097CICN001' AND \"ifDescription\" = 'Bundle-Ether101') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "IDGS0097CICN001" }
     ]
    }
   ]
  },
  {
   "title": "TMSPXTMCCICN002 | Bundle-Ether101",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'TMSPXTMCCICN002' AND \"ifDescription\" = 'Bundle-Ether101') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "TMSPXTMCCICN002" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CICU001 | Bundle-Ether251",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CICU001' AND \"ifDescription\" = 'Bundle-Ether251') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CICU001" }
     ]
    }
   ]
  },
  {
   "title": "RSCS0075CICU001 | Bundle-Ether253",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'RSCS0075CICU001' AND \"ifDescription\" = 'Bundle-Ether253') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "RSCS0075CICU001" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CICN001 | Bundle-Ether703",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CICN001' AND \"ifDescription\" = 'Bundle-Ether703') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CICN001" }
     ]
    }
   ]
  },
  {
   "title": "KAWS0016CICN002 | Bundle-Ether704",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 118 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Hostname: $tag_hostname | Interface: $tag_ifDescription | $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"ifHCInOctets\", 1m) /8 AS \"Input\", non_negative_derivative(\"ifHCOutOctets\", 1m) /8 AS \"Output\" FROM \"interface\" WHERE (\"hostname\" = 'KAWS0016CICN002' AND \"ifDescription\" = 'Bundle-Ether704') AND $timeFilter GROUP BY \"ifDescription\", \"ifAlias\", \"agent_host\",\"hostname\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "KAWS0016CICN002" }
     ]
    }
   ]
  }
 ]
}